image: franzos/jekyll-node-python-awscli:v0.4

cache:
  paths:
    - vendor/
    - .npm/

before_script:
  - apt-get install libruby2.5
  - bundle install --path vendor
  - gem pristine ffi

website:
  stage: deploy
  script:
    - echo "=> Building web version ..."
    - JEKYLL_ENV=production bundle exec jekyll build -d _site/
    - echo "=> Upload to Website"
    - export AWS_S3_BUCKET=wiki.pantherx.org
    - export LOCAL_AWS_CLOUDFRONT_DISTRIBUTION_ID="$(echo "$LOCAL_AWS_CLOUDFRONT_DISTRIBUTION_ID")"
    - export LOCAL_AWS_ACCESS_KEY_ID="$(echo "$LOCAL_AWS_ACCESS_KEY_ID")"
    - export LOCAL_AWS_SECRET_ACCESS_KEY="$(echo "$LOCAL_AWS_SECRET_ACCESS_KEY")"
    - aws s3 sync _site/ s3://${AWS_S3_BUCKET} --delete
    - aws cloudfront create-invalidation --distribution-id $LOCAL_AWS_CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
  only:
    - master