title: "PantherX Operating System Wiki"
description: "A growing collection of information on how-to accomplish things on PantherX OS"
baseurl: ""
url: ""
assets: "/assets"

type: web

permalink: /:title/

exclude:
  - src/
  - gulpfile.js
  - package.json
  - yarn.lock
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .idea
  - .bit.json
  - .bitmap
  - yarn-error.log
  - bit.json
  - s3_website.yml
  - project.config
  - run.sh

defaults:
  - scope:
      path: ""
    values:
      layout: wiki-docs

sections:
  distribution:
    - title: PantherX OS
      description: Overview of PantherX OS
    - title: Frequently asked questions
      description: Notable questions and facts
    - title: PantherX compared to other distributions
      description: Summarises the similarities and differences between PantherX and other distributions.
    - title: Installation guide
      description: Guide through the process of installing PantherX Linux.
    - title: General recommendations
      description: Annotated index of post-installation tutorials and other popular articles.
    #- title: List of applications
    #  description: Categorised presentation of common official and 3rd party packages.
  community:
    - title: Getting involved
      description: Describes various ways you can contribute to the Panther community.

nav:
  - title: Home
    url: https://www.pantherx.org/
  - title: PantherX OS
    url: https://www.pantherx.org/#PantherX+Operating+System
  - title: PantherX for Business
    url: https://www.pantherx.org/for-small-business/
  - title: Packages
    url: https://www.pantherx.org/packages/
  - title: Wiki
    url: /
  - title: Community
    url: https://community.pantherx.org
  - title: Contact
    url: https://www.pantherx.org/contact/

sidebar:
  overview:
    - Main page
    - Table of contents
    - Getting involved
    - Wiki news
    - Search
  interaction:
    - Help
    - Contributing
    - Recent Changes
